name: PremiumPets
version: ${project.version}
main: it.pika.premiumpets.PremiumPets
api-version: 1.14
authors: [Pika]
description: PremiumPets plugin made with love and pizza by Pika
depend: [Vault]
commands:
  premiumpets:
    description: Main command
    aliases: [pet, pets, ppets]